package ee.taltech;// Generated by Selenium IDE


import com.google.common.io.Files;
import io.qameta.allure.Allure;
import io.qameta.allure.Attachment;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import static ee.taltech.SeleniumUtils.*;


/**
 * The type Taltech selenium test.
 */

public class TaltechSeleniumTest {
	/**
	 * The Driver.

	 */
	static WebDriver driver;

	/**
	 * Before all.
	 */
	@BeforeAll
	static void beforeAll() {

		System.setProperty("webdriver.chrome.driver", "C:\\Autotests\\chromedriver.exe");
		ChromeOptions options = getChromeOptions();
		driver = new ChromeDriver(options);
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
	}

	/**
	 * Tear down.
	 */
	@AfterEach
	public void tearDown() {

		ArrayList<String> tabs = new ArrayList<String> (driver.getWindowHandles());
		driver.switchTo().window(tabs.get(0));
	}

	/**
	 * Menu test.
	 *
	 * @param language the language
	 * @param text     the text
	 * @throws IOException the io exception
	 */
// https://www.baeldung.com/parameterized-tests-junit-5
	@ParameterizedTest(name = "{index} {0} : {1}")
	@CsvSource(
			{
					"ENGLISH,Academic calendar",
					"ESTONIAN,Akadeemiline kalender",

					"ENGLISH,Rules",
					"ESTONIAN,Õppekorralduse reeglid",

					"ENGLISH,Internship",
					"ESTONIAN,Praktika",

					"ENGLISH,Regulations and documents",
					"ESTONIAN,Juhendid ja õigusaktid",

					"ENGLISH,Scholarships",
					"ESTONIAN,Stipendiumid",

					"ENGLISH,Tuition fees",
					"ESTONIAN,Õppeteenuste tasumäärad",

					"ENGLISH,Changing the study programme",
					"ESTONIAN,Õppekava vahetamine",

					"ENGLISH,Recognition of prior learning",
					"ESTONIAN,VÕTA",

					"ENGLISH,Academic leave",
					"ESTONIAN,Akadeemiline puhkus",

					"ENGLISH,Minor specialities",
					"ESTONIAN,Kõrvalerialad",

					"ENGLISH,Feedback",
					"ESTONIAN,Tagasiside hea tava",

					"ENGLISH,General information",
					"ESTONIAN,Üldinfo",

					"ENGLISH,Timetable",
					"ESTONIAN,Treeningkalender",

					"ENGLISH,Exchange studies",
					"ESTONIAN,Vahetusõpingud",

					"ENGLISH,Visiting students",
					"ESTONIAN,Külalisüliõpilasena õppimine",

					"ENGLISH,Rules of Study load",
					"ESTONIAN,Õppekoormuse reeglid",

					"ENGLISH,Video guide",
					"ESTONIAN,Videojuhend",

					"ENGLISH,Study Information System",
					"ESTONIAN,ÕIS"
			})
	public void MenuTest(String language, String text) throws IOException {

		try {
			find(driver, language, text).click();
		}
		catch (Exception exception)
		{
			Allure.addAttachment("Element not found!", new ByteArrayInputStream(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES)));
			throw exception;
		}

	}

	/**
	 * After all.
	 */

	@AfterAll
	static void afterAll() {
		driver.quit();
	}
}
